site_name: Sword Chronicle
site_description: Manual de rol - Feudal Fantasy Roleplaying
docs_dir: docs

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Inicio: index.md
  - Reglas del Juego:
    - El Sistema: reglas/sistema.md
    - Pruebas y Dificultad: reglas/pruebas.md
    - Glosario: reglas/glosario.md
  - Creación de Personajes:
    - Introducción y Concepto: creacion/introduccion.md
    - Habilidades y Estadísticas: creacion/asignar-stats.md
    - Recompensas y Resumen: creacion/recompensas.md
  - Habilidades y Especialidades:
    - Resumen: habilidades/resumen.md
    - Detalle: habilidades/detalladas.md
  - Destino y Cualidades:
    - Puntos de Destino: destino/puntos.md
    - Beneficios: destino/beneficios.md
    - Defectos: destino/defectos.md
  - Casa y Tierras:
    - Creación de la Casa: casa/creacion.md
    - Dominios y Tenencias: casa/dominios.md
    - Distinciones y El Hogar: casa/distinciones.md
  - Hechicería:
    - Introducción: magia/introduccion.md
    - Arte de la Bendición: magia/bendicion.md
    - Arte de la Adivinación: magia/adivinacion.md
    - Arte de la Maldición: magia/maldicion.md
    - Arte de la Protección: magia/proteccion.md